# === DAFTAR AYAT WHITELIST (HISAB) ===
HISAB_AYAT_IDS = {
    "TFS-AN-NABA-2-KT", "TFS-AN-NABA-17-KT", "TFS-AN-NABA-18-KT", "TFS-AN-NABA-27-KT",
    "TFS-AN-NABA-29-KT", "TFS-AN-NABA-36-KT", "TFS-AN-NABA-39-KT", "TFS-AN-NABA-40-KT",
    "TFS-AN-NAZI'AT-8-KT", "TFS-AN-NAZI'AT-9-KT", "TFS-AN-NAZI'AT-14-KT", "TFS-AN-NAZI'AT-34-KT",
    "TFS-AN-NAZI'AT-35-KT", "TFS-AN-NAZI'AT-36-KT", "TFS-'ABASA-21-KT", "TFS-'ABASA-22-KT",
    "TFS-'ABASA-33-KT", "TFS-'ABASA-34-KT", "TFS-'ABASA-35-KT", "TFS-'ABASA-36-KT",
    "TFS-'ABASA-38-KT", "TFS-'ABASA-39-KT", "TFS-AT-TAKWIR-10-KT", "TFS-AL-INFITHAR-5-KT",
    "TFS-AL-INFITHAR-13-KT", "TFS-AL-INFITHAR-14-KT", "TFS-AL-INFITHAR-15-KT", "TFS-AL-INFITHAR-16-KT",
    "TFS-AL-MUTHAFFIFIN-4-KT", "TFS-AL-MUTHAFFIFIN-5-KT", "TFS-AL-MUTHAFFIFIN-6-KT",
    "TFS-AL-MUTHAFFIFIN-8-KT", "TFS-AL-MUTHAFFIFIN-9-KT", "TFS-AL-MUTHAFFIFIN-19-KT",
    "TFS-AL-MUTHAFFIFIN-20-KT", "TFS-AL-MUTHAFFIFIN-21-KT", "TFS-AL-INSYIQAQ-7-KT",
    "TFS-AL-INSYIQAQ-8-KT", "TFS-AL-INSYIQAQ-9-KT", "TFS-AL-INSYIQAQ-10-KT",
    "TFS-AL-INSYIQAQ-11-KT", "TFS-AL-INSYIQAQ-12-KT", "TFS-AL-INSYIQAQ-16-KT",
    "TFS-AL-INSYIQAQ-17-KT", "TFS-AL-INSYIQAQ-18-KT", "TFS-AL-INSYIQAQ-19-KT",
    "TFS-AL-BURUUJ-2-KT", "TFS-AL-GHASYIYAH-25-KT", "TFS-AL-GHASYIYAH-26-KT",
    "TFS-AL-FAJR-21-KT", "TFS-AL-FAJR-22-KT", "TFS-AL-FAJR-23-KT", "TFS-AL-BALAD-6-KT",
    "TFS-AL-BALAD-7-KT", "TFS-Al-'ALAQ-8-KT", "TFS-AZ-ZALZALAH-4-KT", "TFS-AZ-ZALZALAH-5-KT",
    "TFS-AZ-ZALZALAH-6-KT", "TFS-AZ-ZALZALAH-7-KT", "TFS-AZ-ZALZALAH-8-KT",
    "TFS-AL-ADIYAT-9-KT", "TFS-AL-ADIYAT-10-KT", "TFS-AL-ADIYAT-11-KT",
    "TFS-AL-QARI'AH-6-KT", "TFS-AL-QARI'AH-7-KT", "TFS-AL-QARI'AH-8-KT",
    "TFS-AL-QARI'AH-9-KT", "TFS-AL-QARI'AH-10-KT", "TFS-AL-QARI'AH-11-KT",
}

# === BLACKLIST UNTUK MIZAN ===
MIZAN_BLACKLIST_AYAT_IDS = {
    "TFS-AL-QARI'AH-1-KT", "TFS-AL-QARI'AH-2-KT", "TFS-AL-QARI'AH-3-KT",
    "TFS-AL-QARI'AH-4-KT", "TFS-AL-QARI'AH-5-KT", "TFS-AN-NAZI'AT-6-KT",
    "TFS-AN-NAZI'AT-7-KT", "TFS-AT-TAKWIR-1-KT", "TFS-AT-TAKWIR-2-KT",
}

# === MAPPING NAMA SURAT WHITELIST → NAMA DI DATABASE ===
SURAT_DB_MAP = {
    "'ABASA": "Abasa",
    "ABASA": "Abasa",
    "AL-QARI'AH": "Al-Qari'ah",
    "AL-QARIAH": "Al-Qari'ah",
    "AL-INFITHAR": "Al-Infitar",
    "AL-INFITAR": "Al-Infitar",
    "AL-MUTHAFFIFIN": "Al-Mutaffifin",
    "AL-MUTAFFIFIN": "Al-Mutaffifin",
    "AL-INSYIQAQ": "Al-Insyiqaq",
    "AL-INSYIQOQ": "Al-Insyiqaq",
    "AL-GHASYIYAH": "Al-Ghasyiyah",
    "AL-GHASHIYAH": "Al-Ghasyiyah",
    "AN-NAZI'AT": "An-Nazi'at",
    "AN-NAZIAT": "An-Nazi'at",
    "AL-FAJR": "Al-Fajr",
    "AZ-ZALZALAH": "Az-Zalzalah",
    "AL-ADIYAT": "Al-'Adiyat",
    "AL-'ALAQ": "Al-'Alaq",
    "AL-BURUUJ": "Al-Buruj",
    "AL-BURUJ": "Al-Buruj",
    "AL-BURRUJ": "Al-Buruj",
}

# === NORMALISASI & AYAT ID ===
SURAT_NAME_VARIANTS = {
    "AL-BURUJ": ["AL-BURUJ", "AL-BURUUJ", "AL-BURRUJ"],
    "AN-NABA": ["AN-NABA", "AN-NABA'", "AN-NABA'"],
    "AN-NAZI'AT": ["AN-NAZI'AT", "AN-NAZIAT", "AN-NAZI'AT"],
    "'ABASA": ["'ABASA", "ABASA", "'ABASA"],
    "AL-INFITHAR": ["AL-INFITHAR", "AL-INFITAR"],
    "AL-MUTHAFFIFIN": ["AL-MUTHAFFIFIN", "AL-MUTAFFIFIN"],
    "AL-INSYIQAQ": ["AL-INSYIQAQ", "AL-INSYIQOQ", "AL-INSIQAQ"],
    "AL-GHASYIYAH": ["AL-GHASYIYAH", "AL-GHASHIYAH", "AL-GHASIYAH"],
    "AZ-ZALZALAH": ["AZ-ZALZALAH", "AL-ZALZALAH"],
    "AL-ADIYAT": ["AL-ADIYAT", "AL-'ADIYAT"],
    "AL-QARI'AH": ["AL-QARI'AH", "AL-QARIAH"],
    "AT-TAKWIR": ["AT-TAKWIR", "AT-TAKWEER"],
    "AL-'ALAQ": ["AL-'ALAQ", "AL-ALAQ"],
    "AL-FAJR": ["AL-FAJR", "AL-FAJAR"],
    "AL-BALAD": ["AL-BALAD"],
}